# Build stage
FROM golang:1.20 AS builder

WORKDIR /app
COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server server/main.go

# Final stage
FROM alpine:latest

WORKDIR /app

RUN apk add bash

COPY --from=builder /app/config.yaml /app/config.yaml
COPY --from=builder /app/server/ /app/

CMD ["/app/main"]